### ISSUE TITLE
update opam description: int8, int16

### ISSUE THREAD

**Issue by cfcs** [hannesm/randomconv#3]
Hey, the opam description and the description in the mli mentions `int32, int` etc, but it doesn't mention e.g. `int16`.

**Comment by cfcs** [comment]
Thanks for updating.

It sounds a bit pedantic, but it's still not [mentioned in the .mli](https://github.com/hannesm/randomconv/blob/master/randomconv.mli#L4), this can be a bit confusing when browsing the interface through `ocp-browser` which I find is the easiest way to look up information about OCaml libraries when developing.

**Comment by hannesm** [comment]
I hope 85de0ea addresses your concern (released as 0.1.2 https://github.com/ocaml/opam-repository/pull/13477)
